-----------Super Admin---------------
USE [master]
GO
CREATE LOGIN [SuperAdmin] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [SuperAdmin]
GO
use [DW_GUANA_HOSPI];
GO
use [master];
GO
USE [DW_GUANA_HOSPI]
GO
CREATE USER [SuperAdmin] FOR LOGIN [SuperAdmin]
GO
USE [DW_GUANA_HOSPI]
GO
ALTER USER [SuperAdmin] WITH DEFAULT_SCHEMA=[SuperAdmin]
GO
USE [DW_GUANA_HOSPI]
GO
CREATE SCHEMA [SuperAdmin] AUTHORIZATION [SuperAdmin]
GO
USE [DW_GUANA_HOSPI]
GO
ALTER ROLE [db_owner] ADD MEMBER [SuperAdmin]
GO
use [GUANA_HOSPI];
GO
use [DW_GUANA_HOSPI];
GO
USE [GUANA_HOSPI]
GO
CREATE USER [SuperAdmin] FOR LOGIN [SuperAdmin]
GO
USE [GUANA_HOSPI]
GO
ALTER USER [SuperAdmin] WITH DEFAULT_SCHEMA=[SuperAdmin]
GO
USE [GUANA_HOSPI]
GO
CREATE SCHEMA [SuperAdmin] AUTHORIZATION [SuperAdmin]
GO
USE [GUANA_HOSPI]
GO
ALTER ROLE [db_owner] ADD MEMBER [SuperAdmin]
GO

-----------Admin---------------
USE [master]
GO
CREATE LOGIN [admin] WITH PASSWORD=N'12345', DEFAULT_DATABASE=[GUANA_HOSPI], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [DW_GUANA_HOSPI];
GO
use [master];
GO
USE [DW_GUANA_HOSPI]
GO
CREATE USER [admin] FOR LOGIN [admin]
GO
USE [DW_GUANA_HOSPI]
GO
ALTER USER [admin] WITH DEFAULT_SCHEMA=[admin]
GO
USE [DW_GUANA_HOSPI]
GO
CREATE SCHEMA [admin] AUTHORIZATION [admin]
GO
USE [DW_GUANA_HOSPI]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [admin]
GO
use [GUANA_HOSPI];
GO
use [DW_GUANA_HOSPI];
GO
USE [GUANA_HOSPI]
GO
CREATE USER [admin] FOR LOGIN [admin]
GO
USE [GUANA_HOSPI]
GO
ALTER USER [admin] WITH DEFAULT_SCHEMA=[admin]
GO
USE [GUANA_HOSPI]
GO
CREATE SCHEMA [admin] AUTHORIZATION [admin]
GO
USE [GUANA_HOSPI]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [admin]
GO
USE [GUANA_HOSPI]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [admin]
GO